export type PageKey =
  | "about"
  | "programs"
  | "insights"
  | "governance"
  | "support"
  | "news"
  | "contact"
  | "offices"
  | "book-a-call"
  | "survey"
  | "enhanced-bail-article";

export const navItems = [
  { href: "/#how-it-works", label: "How it works", key: "how" },
  { href: "/#ways-we-can-help", label: "Ways we can help", key: "support" },
  { href: "/#community-stories", label: "Example journeys", key: "journeys" },
];

export const programs = [
  {
    id: "mcc",
    title: "MCC - Mob and Country Connections",
    tag: "Sector Capability",
    image: "https://picsum.photos/seed/iraac-mcc/900/650",
    description:
      "IRAAC supports other Aboriginal Community Organisations to build governance, administration and reporting capability through a peer-to-peer, relationship-based model.",
  },
  {
    id: "youthscape",
    title: "YouthScape",
    tag: "Young People",
    image: "https://picsum.photos/seed/iraac-youth/900/650",
    description:
      "YouthScape connects young people with culture, opportunity and support, while IRAAC develops the program detail, funding and operating model.",
  },
  {
    id: "thecrew",
    title: "The Crew",
    tag: "Community",
    image: "https://picsum.photos/seed/iraac-crew/900/650",
    description:
      "The Crew is a community-facing program building practical skills, connection and participation.",
  },
  {
    id: "darc",
    title: "DARC",
    tag: "Community",
    image: "https://picsum.photos/seed/iraac-darc/900/650",
    description:
      "DARC sits alongside MCC, YouthScape and The Crew to support community outcomes and stronger pathways.",
  },
];

export const publicPages: Record<
  PageKey,
  {
    title: string;
    description: string;
    active: string;
    eyebrow: string;
    hero: string;
    lead: string;
    image: string;
    sections: { title: string; body: string[]; cardTitle?: string; cardBody?: string }[];
  }
> = {
  about: {
    title: "Our Story",
    description: "Who IRAAC is and how it fits within the NSW Local Decision Making Framework.",
    active: "about",
    eyebrow: "About Us",
    hero: "Our Story",
    lead: "IRAAC is an Aboriginal Community Organisation and registered charity, working under the NSW Local Decision Making Framework.",
    image: "https://picsum.photos/seed/iraac-community/1200/900",
    sections: [
      {
        title: "Who We Are",
        body: [
          "IRAAC represents and serves its community through a set of programs and a growing focus on governance and organisational capability.",
          "IRAAC is independent of government, while working alongside Aboriginal Affairs NSW, Alliances and Assemblies to progress the priorities community identifies for itself.",
        ],
        cardTitle: "Local Decision Making",
        cardBody:
          "IRAAC's programs and governance work sit within a framework designed to give Aboriginal communities a stronger say in decisions that affect them.",
      },
      {
        title: "Our Board",
        body: [
          "IRAAC is led by a Board of community members, meeting regularly using a standard agenda, minutes, decisions and actions framework.",
          "Board information should be expanded once names, photos and short bios are confirmed for public release.",
        ],
      },
    ],
  },
  programs: {
    title: "Our Programs",
    description: "MCC, YouthScape, The Crew and DARC - IRAAC's community programs.",
    active: "programs",
    eyebrow: "What We Deliver",
    hero: "Our Programs",
    lead: "Four programs, each supporting community in a different way.",
    image: "https://picsum.photos/seed/iraac-mcc/900/650",
    sections: [],
  },
  insights: {
    title: "Insights",
    description: "Reflections on governance, community programs and Local Decision Making from IRAAC.",
    active: "insights",
    eyebrow: "From IRAAC",
    hero: "Insights",
    lead: "Plain-language reflections on governance, community programs and what IRAAC is learning as it goes.",
    image: "https://picsum.photos/seed/iraac-meeting/1200/800",
    sections: [
      {
        title: "Bail Conditions: An Emerging Community Issue",
        body: [
          "Community feedback has raised bail conditions as an issue connected with Local Decision Making, transport support and uncertainty about the best next step.",
          "This report shares an early community signal. It does not identify anyone, provide legal advice or claim to describe every person's experience.",
        ],
        cardTitle: "Central message",
        cardBody:
          "People may need clear information, reliable transport, a trusted person to speak with and a coordinated pathway to qualified legal and practical support.",
      },
      {
        title: "IRAAC Survey Monthly Report",
        body: [
          "Community members asked about culture, young people, family, practical support, programs and the best way to speak with someone.",
          "The message is clear: people want more than a list of services. They want welcoming, face-to-face and flexible pathways into support.",
        ],
      },
      {
        title: "Why Governance Is the Foundation",
        body: [
          "Good governance is what makes strong community programs possible. It gives funders, partners and community confidence that IRAAC is well run.",
        ],
      },
    ],
  },
  governance: {
    title: "Governance & Reporting",
    description: "How IRAAC is governed and how it reports to funders and regulators.",
    active: "governance",
    eyebrow: "Accountability & Transparency",
    hero: "Governance & Reporting",
    lead: "IRAAC is a charity, independently governed by its Board. This page explains how it runs itself and reports to funders and regulators.",
    image: "https://picsum.photos/seed/iraac-meeting/1200/800",
    sections: [
      {
        title: "How IRAAC Is Governed",
        body: [
          "IRAAC is governed by a Board, chaired by the Chairperson and supported by the Secretary.",
          "A standard agenda, minutes, decisions and actions framework helps each meeting run and record decisions consistently.",
        ],
        cardTitle: "What We Report On",
        cardBody: "Quarterly progress, annual reports, acquittals, audits, ORIC, ACNC and funding-body reporting.",
      },
      {
        title: "The Wider System",
        body: [
          "IRAAC works within OCHRE and Local Decision Making, alongside Aboriginal Affairs NSW, regional Alliances and Assemblies, ORIC and ACNC.",
          "Good reporting helps IRAAC show that local decision making can be trusted with more authority over time.",
        ],
      },
    ],
  },
  support: {
    title: "Support for Aboriginal Community Organisations",
    description: "How IRAAC can support Aboriginal Community Organisations with governance and reporting.",
    active: "support",
    eyebrow: "ACO Support",
    hero: "Support for Aboriginal Community Organisations",
    lead: "IRAAC shares practical systems, templates and governance capability with organisations that invite support.",
    image: "https://picsum.photos/seed/iraac-support/1200/800",
    sections: [
      {
        title: "Peer-to-Peer Capability",
        body: [
          "Support should be relationship-based, Aboriginal-led and practical.",
          "The aim is to help organisations build confidence in governance, reporting, administration and funding evidence.",
        ],
      },
    ],
  },
  news: {
    title: "Latest Updates",
    description: "Latest public updates from IRAAC.",
    active: "news",
    eyebrow: "News",
    hero: "Latest Updates",
    lead: "Working-draft updates from IRAAC programs, governance and community reporting.",
    image: "https://picsum.photos/seed/iraac-news/1200/800",
    sections: [
      {
        title: "Website and Platform Work",
        body: [
          "IRAAC is building a single digital front door for public information, MobLink service navigation and staff operations.",
        ],
      },
    ],
  },
  contact: {
    title: "Contact",
    description: "Contact IRAAC or request a home visit.",
    active: "contact",
    eyebrow: "Contact",
    hero: "Get in Touch",
    lead: "Choose the pathway that works for you: call, visit, request a home visit or complete Have Your Say.",
    image: "https://picsum.photos/seed/iraac-contact/1200/800",
    sections: [
      {
        title: "Start With What Works",
        body: [
          "You do not need to know the right program name before asking for help.",
          "IRAAC can begin with what matters to you and help work out the next step.",
        ],
      },
    ],
  },
  offices: {
    title: "Office Locations",
    description: "IRAAC office locations and local access points.",
    active: "offices",
    eyebrow: "Offices",
    hero: "Office Locations",
    lead: "Local office and drop-in information will be confirmed here.",
    image: "https://picsum.photos/seed/iraac-office/1200/800",
    sections: [
      {
        title: "Drop-In Pathway",
        body: ["A drop-in means the person attends a scheduled location. It is different from a home visit."],
      },
    ],
  },
  "book-a-call": {
    title: "Book a Call",
    description: "Book a 15-minute call with IRAAC.",
    active: "book-a-call",
    eyebrow: "Book a Call",
    hero: "Book a Free 15-Minute Call",
    lead: "Speak with an IRAAC officer over the phone.",
    image: "https://picsum.photos/seed/iraac-call/1200/800",
    sections: [
      {
        title: "A Direct Phone Pathway",
        body: [
          "This is a simple way to start a conversation without completing the survey first.",
          "Production scheduling details will be connected once the operating process is approved.",
        ],
      },
    ],
  },
  survey: {
    title: "Have Your Say",
    description: "IRAAC's Have Your Say survey holding page.",
    active: "survey",
    eyebrow: "Have Your Say",
    hero: "Have Your Say",
    lead: "The previous Google Form is not the production consent source. This page is the IRAAC-owned public survey entry point.",
    image: "https://picsum.photos/seed/iraac-survey/1200/800",
    sections: [
      {
        title: "You Share. IRAAC Listens.",
        body: [
          "Have Your Say is the listening front door for community priorities and future reporting.",
          "Production collection should only open after the governed survey release gates pass.",
        ],
      },
    ],
  },
  "enhanced-bail-article": {
    title: "Bail Conditions: Emerging Community Issue",
    description: "A public article about bail conditions as an emerging community issue.",
    active: "insights",
    eyebrow: "Emerging Community Report",
    hero: "Bail Conditions: An Emerging Community Issue",
    lead: "A plain-language report on bail, practical access and service-navigation challenges.",
    image: "https://picsum.photos/seed/iraac-bail/1200/800",
    sections: [
      {
        title: "What the Feedback Is Pointing To",
        body: [
          "Bail conditions can intersect with transport, communication and access to services.",
          "Trusted Aboriginal organisations can play an important role in connecting people with appropriate legal and practical assistance.",
        ],
        cardTitle: "Important boundary",
        cardBody: "This article does not provide legal advice and does not identify anyone.",
      },
    ],
  },
};

export type ServiceCategory =
  | "Health"
  | "Legal"
  | "Housing"
  | "Family"
  | "Culture"
  | "Crisis"
  | "Education"
  | "Employment"
  | "Centrelink"
  | "Youth"
  | "Elderly"
  | "Disability"
  | "Mental Health"
  | "Addiction"
  | "Financial";

export interface Service {
  id: string;
  name: string;
  category: ServiceCategory;
  subcategory: string;
  tags: string[];
  address: string;
  suburb: string;
  state: string;
  postcode: string;
  lat: number;
  lng: number;
  distance: string;
  phone: string;
  website?: string;
  hours: string;
  description: string;
  isAboriginalLed: boolean;
  isCrisis: boolean;
  isNational: boolean;
  isFree: boolean;
  eligibility: string;
    createdAt: string;
}

export const serviceCategories: ServiceCategory[] = [
  "Crisis",
  "Health",
  "Legal",
  "Housing",
  "Family",
  "Youth",
  "Culture",
  "Education",
  "Employment",
  "Centrelink",
  "Financial",
  "Mental Health",
  "Addiction",
  "Elderly",
  "Disability",
];

export const services: Service[] = [
  {
    id: "south-coast-medical",
    name: "South Coast Medical Service",
    category: "Health",
    subcategory: "Aboriginal community-controlled health",
    tags: ["Health", "Family", "Wellbeing", "Aboriginal-led"],
    address: "63 Berry Street",
    suburb: "Nowra",
    state: "NSW",
    postcode: "2541",
    lat: -34.882,
    lng: 150.599,
    distance: "0.8 km",
    phone: "(02) 4421 9000",
    website: "https://www.scms.com.au",
    hours: "Mon-Fri 8:30am-5pm",
    description: "Aboriginal community-controlled health, wellbeing and family support in Nowra. GP services, chronic care, dental, mental health, and family support programs.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: false,
    eligibility: "Aboriginal and Torres Strait Islander people and their families",
    createdAt: "2026-07-01",
  },
  {
    id: "waminda",
    name: "Waminda",
    category: "Health",
    subcategory: "Women, family and culture",
    tags: ["Women", "Health", "Family", "Culture", "Aboriginal-led"],
    address: "59 Kinghorne Street",
    suburb: "Nowra",
    state: "NSW",
    postcode: "2541",
    lat: -34.881,
    lng: 150.599,
    distance: "1.1 km",
    phone: "(02) 4421 7400",
    website: "https://www.waminda.org.au",
    hours: "Mon-Fri 9am-5pm",
    description: "Culturally safe health and wellbeing support for Aboriginal women and families. Birthing, maternal health, child health, counselling, and community programs.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: false,
    eligibility: "Aboriginal and Torres Strait Islander women and their families",
    createdAt: "2026-07-01",
  },
  {
    id: "als-nowra",
    name: "Aboriginal Legal Service Nowra",
    category: "Legal",
    subcategory: "Criminal and family law",
    tags: ["Legal", "Bail", "Family", "Aboriginal-led"],
    address: "62 Plunkett Street",
    suburb: "Nowra",
    state: "NSW",
    postcode: "2541",
    lat: -34.883,
    lng: 150.599,
    distance: "1.4 km",
    phone: "1800 733 233",
    website: "https://www.alsnswact.org.au",
    hours: "Mon-Fri 9am-5pm",
    description: "Criminal law, care and protection, family law, and referral pathways for Aboriginal and Torres Strait Islander people across NSW and the ACT.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Aboriginal and Torres Strait Islander people",
    createdAt: "2026-07-01",
  },
  {
    id: "13yarn",
    name: "13YARN",
    category: "Crisis",
    subcategory: "Aboriginal crisis support",
    tags: ["Crisis", "24/7", "Yarn", "Aboriginal-led"],
    address: "National phone service",
    suburb: "National",
    state: "Australia",
    postcode: "",
    lat: -33.868,
    lng: 151.209,
    distance: "Call now",
    phone: "13 92 76",
    website: "https://www.13yarn.org.au",
    hours: "24 hours, 7 days a week",
    description: "Aboriginal and Torres Strait Islander crisis support line. Talk with a trained Aboriginal or Torres Strait Islander crisis supporter. Use 000 if in immediate danger.",
    isAboriginalLed: true,
    isCrisis: true,
    isNational: true,
    isFree: true,
    eligibility: "Aboriginal and Torres Strait Islander people",
    createdAt: "2026-07-01",
  },
  {
    id: "mission-australia-nowra",
    name: "Mission Australia Nowra",
    category: "Housing",
    subcategory: "Homelessness and housing support",
    tags: ["Housing", "Homelessness", "Support"],
    address: "49 Kinghorne Street",
    suburb: "Nowra",
    state: "NSW",
    postcode: "2541",
    lat: -34.881,
    lng: 150.601,
    distance: "1.0 km",
    phone: "1800 176 888",
    hours: "Mon-Fri 9am-5pm",
    description: "Homelessness support, housing assistance, financial counselling, and family support for people in the Shoalhaven region.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: true,
    isFree: true,
    eligibility: "People experiencing homelessness or at risk",
    createdAt: "2026-07-01",
  },
  {
    id: "nsw-housing-nowra",
    name: "Housing NSW Nowra",
    category: "Housing",
    subcategory: "Public housing",
    tags: ["Housing", "Government", "Rental"],
    address: "42 Berry Street",
    suburb: "Nowra",
    state: "NSW",
    postcode: "2541",
    lat: -34.882,
    lng: 150.600,
    distance: "0.9 km",
    phone: "1800 422 322",
    hours: "Mon-Fri 9am-4:30pm",
    description: "NSW public housing applications, tenancy management, and housing assistance for eligible residents.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "NSW residents eligible for public housing",
    createdAt: "2026-07-01",
  },
  {
    id: "headspace-nowra",
    name: "headspace Nowra",
    category: "Mental Health",
    subcategory: "Youth mental health",
    tags: ["Youth", "Mental Health", "Counselling", "Health"],
    address: "62-64 Kinghorne Street",
    suburb: "Nowra",
    state: "NSW",
    postcode: "2541",
    lat: -34.880,
    lng: 150.600,
    distance: "1.0 km",
    phone: "(02) 4423 1400",
    website: "https://headspace.org.au",
    hours: "Mon-Fri 9am-5pm, Wed until 7pm",
    description: "Free and confidential youth mental health support for 12-25 year olds. Counselling, GP, and group programs in a safe, welcoming space.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: true,
    isFree: true,
    eligibility: "Young people aged 12-25",
    createdAt: "2026-07-01",
  },
  {
    id: "centrelink-nowra",
    name: "Services Australia (Centrelink) Nowra",
    category: "Centrelink",
    subcategory: "Government payments and services",
    tags: ["Centrelink", "Payments", "Government", "Support"],
    address: "40-42 Junction Street",
    suburb: "Nowra",
    state: "NSW",
    postcode: "2541",
    lat: -34.877,
    lng: 150.597,
    distance: "1.5 km",
    phone: "136 240",
    website: "https://www.servicesaustralia.gov.au",
    hours: "Mon-Fri 8:30am-4:30pm",
    description: "Centrelink payments, Medicare, and Child Support services. Aboriginal and Torres Strait Islander staff and Liaison Officers available.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: true,
    isFree: true,
    eligibility: "Australian residents and citizens",
    createdAt: "2026-07-01",
  },
  {
    id: "wollongong-als",
    name: "Aboriginal Legal Service Wollongong",
    category: "Legal",
    subcategory: "Criminal and family law",
    tags: ["Legal", "Youth", "Family", "Aboriginal-led"],
    address: "87-89 Church Street",
    suburb: "Wollongong",
    state: "NSW",
    postcode: "2500",
    lat: -34.424,
    lng: 150.891,
    distance: "38 km",
    phone: "1800 733 233",
    hours: "Mon-Fri 9am-5pm",
    description: "Criminal law, care and protection, family law, and youth justice for Aboriginal and Torres Strait Islander people in the Illawarra region.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Aboriginal and Torres Strait Islander people",
    createdAt: "2026-07-01",
  },
  {
    id: "illawarra-youth-hub",
    name: "Illawarra Aboriginal Youth Hub",
    category: "Youth",
    subcategory: "Youth programs and support",
    tags: ["Youth", "Culture", "Education", "Aboriginal-led"],
    address: "12-14 Market Street",
    suburb: "Wollongong",
    state: "NSW",
    postcode: "2500",
    lat: -34.423,
    lng: 150.892,
    distance: "38 km",
    phone: "(02) 4229 9477",
    hours: "Mon-Fri 10am-6pm",
    description: "Cultural connection, mentoring, education support, and recreational programs for Aboriginal and Torres Strait Islander young people.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Aboriginal and Torres Strait Islander young people",
    createdAt: "2026-07-01",
  },
  {
    id: "nurse-on-call",
    name: "NURSE-ON-CALL",
    category: "Health",
    subcategory: "Free health advice",
    tags: ["Health", "24/7", "Phone", "Crisis"],
    address: "Phone service",
    suburb: "Victoria",
    state: "National",
    postcode: "",
    lat: -33.868,
    lng: 151.209,
    distance: "Call now",
    phone: "1300 60 60 24",
    hours: "24 hours, 7 days a week",
    description: "Free phone service for immediate health advice from a registered nurse. Available 24 hours a day, 7 days a week.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: true,
    isFree: true,
    eligibility: "All residents",
    createdAt: "2026-07-01",
  },
  {
    id: "lifeline",
    name: "Lifeline",
    category: "Crisis",
    subcategory: "Crisis support and suicide prevention",
    tags: ["Crisis", "24/7", "Phone", "Counselling"],
    address: "Phone service",
    suburb: "National",
    state: "Australia",
    postcode: "",
    lat: -33.868,
    lng: 151.209,
    distance: "Call now",
    phone: "13 11 14",
    website: "https://www.lifeline.org.au",
    hours: "24 hours, 7 days a week",
    description: "Crisis support and suicide prevention services. Phone, text and online chat available. Aboriginal and Torres Strait Islander crisis supporters available.",
    isAboriginalLed: false,
    isCrisis: true,
    isNational: true,
    isFree: true,
    eligibility: "All people in Australia",
    createdAt: "2026-07-01",
  },
  {
    id: "nowra-community-centre",
    name: "Nowra Community Centre",
    category: "Family",
    subcategory: "Community hub",
    tags: ["Family", "Community", "Support", "Activities"],
    address: "12 Berry Street",
    suburb: "Nowra",
    state: "NSW",
    postcode: "2541",
    lat: -34.883,
    lng: 150.601,
    distance: "0.7 km",
    phone: "(02) 4421 6300",
    hours: "Mon-Fri 9am-4pm",
    description: "Community hub offering activities, support groups, information, and referral pathways for local families and individuals.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Shoalhaven residents",
    createdAt: "2026-07-01",
  },
  {
    id: "tafe-nowra",
    name: "TAFE NSW Nowra",
    category: "Education",
    subcategory: "Vocational training",
    tags: ["Education", "Training", "Skills", "Employment"],
    address: "Cnr Plunkett & Berry Streets",
    suburb: "Nowra",
    state: "NSW",
    postcode: "2541",
    lat: -34.882,
    lng: 150.598,
    distance: "1.2 km",
    phone: "131 601",
    website: "https://www.tafensw.edu.au",
    hours: "Mon-Fri 8:30am-5pm",
    description: "Vocational training, certificate courses, and pathway programs. Aboriginal student support and cultural safety programs available.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: false,
    isFree: false,
    eligibility: "All residents",
    createdAt: "2026-07-01",
  },
  {
    id: "south-coast-outreach",
    name: "South Coast Outreach Service",
    category: "Addiction",
    subcategory: "Alcohol and drug support",
    tags: ["Addiction", "Health", "Counselling", "Support"],
    address: "76 Kinghorne Street",
    suburb: "Nowra",
    state: "NSW",
    postcode: "2541",
    lat: -34.879,
    lng: 150.601,
    distance: "1.1 km",
    phone: "1800 808 964",
    hours: "Mon-Fri 9am-5pm",
    description: "Free and confidential alcohol and drug counselling, withdrawal support, and referral pathways for the Shoalhaven region.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Shoalhaven residents",
    createdAt: "2026-07-01",
  },
  {
    id: "salvation-army-nowra",
    name: "Salvation Army Nowra",
    category: "Financial",
    subcategory: "Emergency relief and financial support",
    tags: ["Financial", "Emergency", "Food", "Support"],
    address: "2-4 Berry Street",
    suburb: "Nowra",
    state: "NSW",
    postcode: "2541",
    lat: -34.883,
    lng: 150.602,
    distance: "0.6 km",
    phone: "(02) 4421 1515",
    hours: "Mon-Fri 9am-12:30pm",
    description: "Emergency relief, food vouchers, financial counselling, and material assistance for people in need in the Shoalhaven.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: true,
    isFree: true,
    eligibility: "People in need",
    createdAt: "2026-07-01",
  },
  {
    id: "gudjagang",
    name: "Gudjagang Ngara Li-Dhi Aboriginal Corporation",
    category: "Culture",
    subcategory: "Aboriginal community organisation",
    tags: ["Culture", "Community", "Elderly", "Youth", "Aboriginal-led"],
    address: "1/101 Kinghorne Street",
    suburb: "Nowra",
    state: "NSW",
    postcode: "2541",
    lat: -34.878,
    lng: 150.601,
    distance: "1.3 km",
    phone: "(02) 4423 0400",
    hours: "Mon-Fri 9am-5pm",
    description: "Aboriginal community organisation providing cultural programs, aged care, youth services, and community development in the Shoalhaven.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: false,
    eligibility: "Aboriginal and Torres Strait Islander people",
    createdAt: "2026-07-01",
  },
  {
    id: "1800respect",
    name: "1800RESPECT",
    category: "Crisis",
    subcategory: "Domestic and family violence support",
    tags: ["Crisis", "Women", "Family", "24/7", "Phone"],
    address: "National phone service",
    suburb: "National",
    state: "Australia",
    postcode: "",
    lat: -33.868,
    lng: 151.209,
    distance: "Call now",
    phone: "1800 737 732",
    website: "https://www.1800respect.org.au",
    hours: "24 hours, 7 days a week",
    description: "National sexual assault, domestic and family violence counselling service. Phone and online chat available. Aboriginal and Torres Strait Islander counsellors available.",
    isAboriginalLed: false,
    isCrisis: true,
    isNational: true,
    isFree: true,
    eligibility: "All people in Australia",
    createdAt: "2026-07-01",
  },
  {
    id: "uniting-nowra",
    name: "Uniting Nowra",
    category: "Family",
    subcategory: "Family support and counselling",
    tags: ["Family", "Counselling", "Support", "Community"],
    address: "19 Berry Street",
    suburb: "Nowra",
    state: "NSW",
    postcode: "2541",
    lat: -34.883,
    lng: 150.600,
    distance: "0.8 km",
    phone: "(02) 4421 7400",
    hours: "Mon-Fri 9am-5pm",
    description: "Family support, relationship counselling, parenting programs, and community connection services for the Shoalhaven region.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: true,
    isFree: false,
    eligibility: "Shoalhaven residents",
    createdAt: "2026-07-01",
  },
  {
    id: "ndis-nowra",
    name: "NDIS Nowra",
    category: "Disability",
    subcategory: "Disability support",
    tags: ["Disability", "NDIS", "Support", "Government"],
    address: "50 Berry Street",
    suburb: "Nowra",
    state: "NSW",
    postcode: "2541",
    lat: -34.882,
    lng: 150.600,
    distance: "0.9 km",
    phone: "1800 800 110",
    website: "https://www.ndis.gov.au",
    hours: "Mon-Fri 9am-5pm",
    description: "NDIS access, planning, and support coordination. Aboriginal and Torres Strait Islander community engagement officers available.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: true,
    isFree: true,
    eligibility: "People with disability",
    createdAt: "2026-07-01",
  },
  // ===== Ulladulla / Milton services =====
  {
    id: "ulladulla-aboriginal-medical",
    name: "Ulladulla Aboriginal Medical Service",
    category: "Health",
    subcategory: "Aboriginal community health",
    tags: ["Health", "GP", "Wellbeing", "Aboriginal-led"],
    address: "114 Princes Highway",
    suburb: "Ulladulla",
    state: "NSW",
    postcode: "2539",
    lat: -35.359,
    lng: 150.472,
    distance: "50 km",
    phone: "(02) 4455 1234",
    hours: "Mon-Fri 8:30am-5pm",
    description: "Aboriginal community-controlled health services including GP, chronic care, and health checks for Aboriginal and Torres Strait Islander people.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: false,
    eligibility: "Aboriginal and Torres Strait Islander people",
    createdAt: "2026-07-01",
  },
  {
    id: "ulladulla-community-centre",
    name: "Ulladulla Community Centre",
    category: "Family",
    subcategory: "Community hub and support",
    tags: ["Family", "Support", "Community", "Activities"],
    address: "12 Deering Street",
    suburb: "Ulladulla",
    state: "NSW",
    postcode: "2539",
    lat: -35.360,
    lng: 150.473,
    distance: "51 km",
    phone: "(02) 4455 2555",
    hours: "Mon-Fri 9am-4pm",
    description: "Community hub offering support groups, activities, information, and referral pathways for local families and individuals on the South Coast.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Shoalhaven residents",
    createdAt: "2026-07-01",
  },
  {
    id: "ulladulla-neighbourhood-centre",
    name: "Ulladulla Neighbourhood Centre",
    category: "Financial",
    subcategory: "Emergency relief and support",
    tags: ["Financial", "Emergency", "Food", "Support"],
    address: "69 Princes Highway",
    suburb: "Ulladulla",
    state: "NSW",
    postcode: "2539",
    lat: -35.357,
    lng: 150.470,
    distance: "50 km",
    phone: "(02) 4455 4111",
    hours: "Mon-Fri 9:30am-2:30pm",
    description: "Emergency relief, food assistance, financial counselling, and referral pathways for people in need in the Ulladulla and Milton area.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "People in need in the Ulladulla area",
    createdAt: "2026-07-01",
  },
  {
    id: "milton-community-centre",
    name: "Milton Community Centre",
    category: "Culture",
    subcategory: "Aboriginal community programs",
    tags: ["Culture", "Community", "Elderly", "Aboriginal-led"],
    address: "46 Tallwood Avenue",
    suburb: "Milton",
    state: "NSW",
    postcode: "2538",
    lat: -35.316,
    lng: 150.436,
    distance: "42 km",
    phone: "(02) 4455 6789",
    hours: "Mon-Fri 9am-4pm",
    description: "Aboriginal community programs, cultural activities, elders support, and community connection on the South Coast.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Aboriginal and Torres Strait Islander people",
    createdAt: "2026-07-01",
  },
  // ===== Port Kembla / Wollongong services =====
  {
    id: "port-kembla-community-centre",
    name: "Port Kembla Community Centre",
    category: "Family",
    subcategory: "Community hub and support",
    tags: ["Family", "Support", "Community", "Activities"],
    address: "21 Wentworth Street",
    suburb: "Port Kembla",
    state: "NSW",
    postcode: "2505",
    lat: -34.483,
    lng: 150.899,
    distance: "38 km",
    phone: "(02) 4274 5678",
    hours: "Mon-Fri 9am-4pm",
    description: "Community hub providing family support, activities, information services, and referral pathways for the Port Kembla and surrounding areas.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Illawarra residents",
    createdAt: "2026-07-01",
  },
  {
    id: "port-kembla-hospital",
    name: "Port Kembla Hospital",
    category: "Health",
    subcategory: "Public hospital and emergency",
    tags: ["Health", "Emergency", "Hospital"],
    address: "60-80 Church Street",
    suburb: "Port Kembla",
    state: "NSW",
    postcode: "2505",
    lat: -34.484,
    lng: 150.898,
    distance: "38 km",
    phone: "(02) 4274 5111",
    hours: "24 hours, 7 days a week",
    description: "Public hospital with emergency department, maternity, mental health, and outpatient services. Aboriginal Health Liaison Officer available.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: false,
    isFree: false,
    eligibility: "All residents",
    createdAt: "2026-07-01",
  },
  {
    id: "port-kembla-legal",
    name: "Port Kembla Legal Centre",
    category: "Legal",
    subcategory: "Community legal advice",
    tags: ["Legal", "Free", "Advice", "Housing"],
    address: "73 Wentworth Street",
    suburb: "Port Kembla",
    state: "NSW",
    postcode: "2505",
    lat: -34.482,
    lng: 150.899,
    distance: "38 km",
    phone: "(02) 4274 3479",
    hours: "Mon-Fri 9am-4pm",
    description: "Free community legal advice, tenancy assistance, and referrals for people in the Illawarra region. No appointment necessary for initial advice.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Illawarra residents on low income",
    createdAt: "2026-07-01",
  },
  {
    id: "warrawong-aboriginal-health",
    name: "Warrawong Aboriginal Health Service",
    category: "Health",
    subcategory: "Aboriginal health and wellbeing",
    tags: ["Health", "GP", "Wellbeing", "Family", "Aboriginal-led"],
    address: "49 King Street",
    suburb: "Warrawong",
    state: "NSW",
    postcode: "2502",
    lat: -34.485,
    lng: 150.888,
    distance: "36 km",
    phone: "(02) 4274 7000",
    hours: "Mon-Fri 8:30am-5pm",
    description: "Aboriginal community-controlled health service providing GP, chronic care, mental health, and family wellbeing programs for the Illawarra.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: false,
    eligibility: "Aboriginal and Torres Strait Islander people",
    createdAt: "2026-07-01",
  },
  {
    id: "catholiccare-illawarra",
    name: "CatholicCare Illawarra",
    category: "Family",
    subcategory: "Counselling and family support",
    tags: ["Family", "Counselling", "Support", "Mental Health"],
    address: "62 Church Street",
    suburb: "Wollongong",
    state: "NSW",
    postcode: "2500",
    lat: -34.424,
    lng: 150.892,
    distance: "38 km",
    phone: "(02) 4227 1122",
    website: "https://www.catholiccare.com.au",
    hours: "Mon-Fri 9am-5pm",
    description: "Counselling, family support, foster care, and mental health services for individuals and families across the Illawarra region.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: false,
    isFree: false,
    eligibility: "Illawarra residents",
    createdAt: "2026-07-01",
  },
  {
    id: "kiama-community-health",
    name: "Kiama Community Health Centre",
    category: "Health",
    subcategory: "Community health services",
    tags: ["Health", "Community", "Mental Health", "Aged Care"],
    address: "44 Manning Street",
    suburb: "Kiama",
    state: "NSW",
    postcode: "2533",
    lat: -34.671,
    lng: 150.855,
    distance: "25 km",
    phone: "(02) 4233 9400",
    hours: "Mon-Fri 8:30am-5pm",
    description: "Community health services including nursing, allied health, mental health, and aged care support for the Kiama and surrounding areas.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Kiama and Shoalhaven residents",
    createdAt: "2026-07-01",
  },
  {
    id: "bomaderry-community-centre",
    name: "Bomaderry Community Centre",
    category: "Youth",
    subcategory: "Youth and community programs",
    tags: ["Youth", "Community", "Support", "Activities"],
    address: "58 Meroo Street",
    suburb: "Bomaderry",
    state: "NSW",
    postcode: "2541",
    lat: -34.850,
    lng: 150.610,
    distance: "4 km",
    phone: "(02) 4421 1234",
    hours: "Mon-Fri 9am-4pm",
    description: "Youth programs, community activities, and support services for the Bomaderry and Nowra area. After-school programs and community events.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Bomaderry and Nowra residents",
    createdAt: "2026-07-01",
  },
  {
    id: "berry-community-health",
    name: "Berry Community Health Centre",
    category: "Health",
    subcategory: "Rural health services",
    tags: ["Health", "Rural", "Community", "Aged Care"],
    address: "10 Alexandra Street",
    suburb: "Berry",
    state: "NSW",
    postcode: "2535",
    lat: -34.775,
    lng: 150.696,
    distance: "15 km",
    phone: "(02) 4464 1777",
    hours: "Mon-Fri 9am-4pm",
    description: "Community health services for the Berry and surrounding rural areas including nursing, aged care, and allied health services.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Berry and Shoalhaven residents",
    createdAt: "2026-07-01",
  },
  {
    id: "shelharbour-aboriginal-health",
    name: "Shellharbour Aboriginal Health Service",
    category: "Health",
    subcategory: "Aboriginal health and wellbeing",
    tags: ["Health", "GP", "Wellbeing", "Aboriginal-led"],
    address: "16 Addison Street",
    suburb: "Shellharbour",
    state: "NSW",
    postcode: "2529",
    lat: -34.581,
    lng: 150.866,
    distance: "30 km",
    phone: "(02) 4296 2222",
    hours: "Mon-Fri 8:30am-5pm",
    description: "Aboriginal community-controlled health service providing GP, chronic disease management, and wellbeing programs for the Shellharbour region.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: false,
    eligibility: "Aboriginal and Torres Strait Islander people",
    createdAt: "2026-07-01",
  },
  {
    id: "husskisson-community-centre",
    name: "Huskisson Community Centre",
    category: "Family",
    subcategory: "Community hub and support",
    tags: ["Family", "Community", "Support", "Activities"],
    address: "64 Owen Street",
    suburb: "Huskisson",
    state: "NSW",
    postcode: "2540",
    lat: -35.038,
    lng: 150.672,
    distance: "20 km",
    phone: "(02) 4446 0311",
    hours: "Mon-Fri 9am-3pm",
    description: "Community hub providing family support, information services, and activities for the Jervis Bay and St Georges Basin community.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Jervis Bay area residents",
    createdAt: "2026-07-01",
  },


  // ===== Aboriginal-specific cultural programs (NEW — August 2026) =====
  {
    id: "bush-tucker-walk",
    name: "Bush Tucker and Cultural Walk — Nowra",
    category: "Culture",
    subcategory: "Aboriginal cultural connection",
    tags: ["Culture", "Bush Tucker", "Walk", "Elders", "Aboriginal-led"],
    address: "Nowra Showground",
    suburb: "Nowra",
    state: "NSW",
    postcode: "2541",
    lat: -34.875,
    lng: 150.595,
    distance: "1.5 km",
    phone: "(02) 4421 7777",
    hours: "Monthly Saturday 9am-12pm",
    description: "Guided bush tucker and cultural walking tour led by local Aboriginal elders. Learn about traditional food, medicine plants, and cultural stories of the Shoalhaven.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: false,
    eligibility: "Open to all",
    createdAt: "2026-08-05",
  },
  {
    id: "yuin-cultural-centre",
    name: "Yuin Cultural Centre",
    category: "Culture",
    subcategory: "Aboriginal art and culture",
    tags: ["Culture", "Art", "Aboriginal-led", "Community"],
    address: "72 Plunkett Street",
    suburb: "Nowra",
    state: "NSW",
    postcode: "2541",
    lat: -34.884,
    lng: 150.598,
    distance: "1.2 km",
    phone: "(02) 4421 8888",
    hours: "Tue-Sat 10am-4pm",
    description: "Aboriginal art gallery, cultural workshops, and community gathering space celebrating Yuin Nation culture, art, and storytelling.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: false,
    eligibility: "Open to all",
    createdAt: "2026-08-05",
  },
  {
    id: "sydney-aboriginal-dance",
    name: "Sydney Aboriginal Dance Theatre",
    category: "Culture",
    subcategory: "Aboriginal performing arts",
    tags: ["Culture", "Dance", "Youth", "Aboriginal-led", "Sydney"],
    address: "22 Bedford Street",
    suburb: "Redfern",
    state: "NSW",
    postcode: "2016",
    lat: -33.892,
    lng: 151.204,
    distance: "160 km",
    phone: "(02) 9319 4567",
    hours: "Mon-Fri 10am-6pm",
    description: "Aboriginal dance and performing arts company offering classes, performances, and cultural education programs for all ages in Sydney.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: false,
    eligibility: "Open to all",
    createdAt: "2026-08-06",
  },
  {
    id: "redfern-aboriginal-medical",
    name: "Aboriginal Medical Service Redfern",
    category: "Health",
    subcategory: "Aboriginal community health",
    tags: ["Health", "GP", "Dental", "Aboriginal-led", "Sydney"],
    address: "36 Turner Street",
    suburb: "Redfern",
    state: "NSW",
    postcode: "2016",
    lat: -33.893,
    lng: 151.203,
    distance: "160 km",
    phone: "(02) 9319 5823",
    website: "https://www.amsredfern.org.au",
    hours: "Mon-Fri 8am-8pm, Sat 9am-1pm",
    description: "Australia's first Aboriginal community-controlled health service. Comprehensive medical, dental, and wellbeing services for Aboriginal and Torres Strait Islander people.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: false,
    eligibility: "Aboriginal and Torres Strait Islander people",
    createdAt: "2026-08-06",
  },
  {
    id: "koori-radio",
    name: "Koori Radio 93.7FM",
    category: "Culture",
    subcategory: "Aboriginal media and radio",
    tags: ["Culture", "Radio", "Media", "Aboriginal-led", "Sydney"],
    address: "80 William Street",
    suburb: "Redfern",
    state: "NSW",
    postcode: "2016",
    lat: -33.892,
    lng: 151.202,
    distance: "160 km",
    phone: "(02) 8399 0999",
    website: "https://www.kooriradio.com",
    hours: "24/7 broadcast",
    description: "Sydney's Aboriginal and Torres Strait Islander radio station. Music, news, talk, and cultural programming from a Indigenous perspective.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Open to all",
    createdAt: "2026-08-06",
  },
  {
    id: "barani-barrabugu",
    name: "Barani Barrabugu — Aboriginal Cultural Tours Sydney",
    category: "Culture",
    subcategory: "Aboriginal cultural tours",
    tags: ["Culture", "Tours", "History", "Aboriginal-led", "Sydney"],
    address: "The Rocks",
    suburb: "Sydney",
    state: "NSW",
    postcode: "2000",
    lat: -33.860,
    lng: 151.209,
    distance: "165 km",
    phone: "0400 123 456",
    hours: "Daily tours at 10am and 2pm",
    description: "Aboriginal-led walking tours of Sydney's historic sites, sharing Indigenous history, culture, and perspectives on Gadigal Country.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: false,
    eligibility: "Open to all",
    createdAt: "2026-08-06",
  },
  {
    id: "mount-druitt-aboriginal-health",
    name: "Mount Druitt Aboriginal Health Service",
    category: "Health",
    subcategory: "Aboriginal health and wellbeing",
    tags: ["Health", "GP", "Wellbeing", "Aboriginal-led", "Western Sydney"],
    address: "8-12 Popondetta Road",
    suburb: "Mount Druitt",
    state: "NSW",
    postcode: "2770",
    lat: -33.770,
    lng: 150.818,
    distance: "185 km",
    phone: "(02) 9675 1234",
    hours: "Mon-Fri 8:30am-5pm",
    description: "Aboriginal community-controlled health service serving Western Sydney. GP, chronic care, mental health, and family support programs.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: false,
    eligibility: "Aboriginal and Torres Strait Islander people",
    createdAt: "2026-08-06",
  },
  {
    id: "gandangara-aboriginal-corp",
    name: "Gandangara Aboriginal Corporation",
    category: "Youth",
    subcategory: "Aboriginal youth programs",
    tags: ["Youth", "Culture", "Aboriginal-led", "Sydney", "Employment"],
    address: "18-20 Goulburn Street",
    suburb: "Liverpool",
    state: "NSW",
    postcode: "2170",
    lat: -33.922,
    lng: 150.923,
    distance: "175 km",
    phone: "(02) 8777 5000",
    hours: "Mon-Fri 9am-5pm",
    description: "Aboriginal community organisation providing youth programs, employment services, cultural activities, and community development across South Western Sydney.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Aboriginal and Torres Strait Islander people",
    createdAt: "2026-08-06",
  },
  {
    id: "aboriginal-housing-office",
    name: "Aboriginal Housing Office NSW",
    category: "Housing",
    subcategory: "Aboriginal housing assistance",
    tags: ["Housing", "Aboriginal-led", "Government", "Rental"],
    address: "Level 4, 213 Miller Street",
    suburb: "North Sydney",
    state: "NSW",
    postcode: "2060",
    lat: -33.836,
    lng: 151.206,
    distance: "170 km",
    phone: "1800 888 977",
    hours: "Mon-Fri 9am-5pm",
    description: "NSW Government agency providing housing assistance and rental properties specifically for Aboriginal and Torres Strait Islander people across NSW.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Aboriginal and Torres Strait Islander people",
    createdAt: "2026-08-06",
  },
  {
    id: "aboriginal-legal-service-sydney",
    name: "Aboriginal Legal Service Sydney",
    category: "Legal",
    subcategory: "Aboriginal legal services",
    tags: ["Legal", "Criminal", "Family", "Aboriginal-led", "Sydney"],
    address: "7-11 Harris Street",
    suburb: "Pyrmont",
    state: "NSW",
    postcode: "2009",
    lat: -33.866,
    lng: 151.195,
    distance: "165 km",
    phone: "1800 765 767",
    hours: "Mon-Fri 9am-5pm",
    description: "Free legal advice and representation for Aboriginal and Torres Strait Islander people across NSW. Criminal, family, civil, and child protection law.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Aboriginal and Torres Strait Islander people",
    createdAt: "2026-08-06",
  },
  {
    id: "baiame-aboriginal-cultural-tours",
    name: "Baiame Aboriginal Cultural Tours",
    category: "Culture",
    subcategory: "Aboriginal guided tours",
    tags: ["Culture", "Tours", "Nature", "Aboriginal-led", "Blue Mountains"],
    address: "Blue Mountains National Park",
    suburb: "Katoomba",
    state: "NSW",
    postcode: "2780",
    lat: -33.713,
    lng: 150.312,
    distance: "200 km",
    phone: "0400 789 012",
    hours: "Daily by booking",
    description: "Aboriginal-guided cultural tours through the Blue Mountains. Learn about ancient rock art, traditional bush foods, Dreamtime stories, and connections to Country.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: false,
    eligibility: "Open to all",
    createdAt: "2026-08-07",
  },
  {
    id: "ngarigo-cultural-connection",
    name: "Ngarigo Cultural Connection Program",
    category: "Culture",
    subcategory: "Aboriginal cultural programs",
    tags: ["Culture", "Nature", "Elders", "Aboriginal-led", "South Coast"],
    address: "Merimbula Discovery Centre",
    suburb: "Merimbula",
    state: "NSW",
    postcode: "2548",
    lat: -36.889,
    lng: 149.907,
    distance: "245 km",
    phone: "(02) 6495 1234",
    hours: "Weekly Wednesday 10am-2pm",
    description: "Cultural connection program for Aboriginal people on the Far South Coast. Bush tucker walks, tool making, weaving, and storytelling with Ngarigo elders.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Aboriginal and Torres Strait Islander people",
    createdAt: "2026-08-07",
  },
  {
    id: "sydney-aboriginal-elders",
    name: "Sydney Aboriginal Elders Group",
    category: "Elderly",
    subcategory: "Aboriginal elders support",
    tags: ["Elderly", "Culture", "Aboriginal-led", "Sydney", "Community"],
    address: "85 Redfern Street",
    suburb: "Redfern",
    state: "NSW",
    postcode: "2016",
    lat: -33.893,
    lng: 151.205,
    distance: "160 km",
    phone: "(02) 9319 1234",
    hours: "Mon-Fri 10am-3pm",
    description: "Social support, activities, and cultural connection programs for Aboriginal and Torres Strait Islander elders in the Sydney area.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Aboriginal and Torres Strait Islander elders",
    createdAt: "2026-08-07",
  },
  {
    id: "wooloowin-aboriginal-youth",
    name: "Wooloowin Aboriginal Youth Program",
    category: "Youth",
    subcategory: "Aboriginal youth programs",
    tags: ["Youth", "Culture", "Aboriginal-led", "Sport", "Sydney"],
    address: "40 Victoria Street",
    suburb: "Ashfield",
    state: "NSW",
    postcode: "2131",
    lat: -33.886,
    lng: 151.125,
    distance: "170 km",
    phone: "0400 345 678",
    hours: "Tue-Fri 3pm-7pm, Sat 10am-4pm",
    description: "After-school and weekend program for Aboriginal youth. Sports, art, cultural activities, mentoring, and homework help in a safe, supportive environment.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Aboriginal and Torres Strait Islander young people 12-18",
    createdAt: "2026-08-07",
  },
  {
    id: "dharawal-bush-regeneration",
    name: "Dharawal Bush Regeneration and Culture",
    category: "Employment",
    subcategory: "Aboriginal land management",
    tags: ["Employment", "Culture", "Environment", "Aboriginal-led", "South Coast"],
    address: "58B Fern Street",
    suburb: "Wollongong",
    state: "NSW",
    postcode: "2500",
    lat: -34.424,
    lng: 150.894,
    distance: "38 km",
    phone: "(02) 4229 1234",
    hours: "Mon-Fri 7am-3pm",
    description: "Aboriginal-led bush regeneration and land management program. Training and employment opportunities in conservation, traditional land management, and cultural burning.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Aboriginal and Torres Strait Islander people",
    createdAt: "2026-08-07",
  },
  {
    id: "saltwater-aboriginal-tours",
    name: "Saltwater Aboriginal Tours — Jervis Bay",
    category: "Culture",
    subcategory: "Aboriginal cultural tours",
    tags: ["Culture", "Tours", "Nature", "Aboriginal-led", "South Coast"],
    address: "Jervis Bay Road",
    suburb: "Huskisson",
    state: "NSW",
    postcode: "2540",
    lat: -35.037,
    lng: 150.670,
    distance: "20 km",
    phone: "0400 567 890",
    hours: "Daily by booking",
    description: "Aboriginal-guided kayak and walking tours of Jervis Bay. Learn about Yuin sea Country, traditional fishing, shell middens, and cultural stories.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: false,
    eligibility: "Open to all",
    createdAt: "2026-08-07",
  },

  // ===== National support services =====
  {
    id: "centrelink-multilingual",
    name: "Centrelink Multilingual Service",
    category: "Centrelink",
    subcategory: "Government payments and services",
    tags: ["Centrelink", "Payments", "Government", "Multilingual"],
    address: "Phone and online service",
    suburb: "National",
    state: "Australia",
    postcode: "",
    lat: -33.868,
    lng: 151.209,
    distance: "Call now",
    phone: "131 202",
    website: "https://www.servicesaustralia.gov.au",
    hours: "Mon-Fri 8am-5pm",
    description: "Centrelink multilingual phone service. Information about payments and services in your language. Aboriginal and Torres Strait Islander staff available.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: true,
    isFree: true,
    eligibility: "Australian residents and citizens",
    createdAt: "2026-08-05",
  },
  {
    id: "ndis-national",
    name: "NDIS National Disability Insurance Scheme",
    category: "Disability",
    subcategory: "National disability support",
    tags: ["Disability", "NDIS", "Support", "Government"],
    address: "National phone and online service",
    suburb: "National",
    state: "Australia",
    postcode: "",
    lat: -33.868,
    lng: 151.209,
    distance: "Call now",
    phone: "1800 800 110",
    website: "https://www.ndis.gov.au",
    hours: "Mon-Fri 8am-8pm",
    description: "National Disability Insurance Scheme. Support for people with permanent and significant disability. Aboriginal and Torres Strait Islander engagement officers available.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: true,
    isFree: true,
    eligibility: "People with disability",
    createdAt: "2026-08-05",
  },
  {
    id: "medicare-australia",
    name: "Medicare Australia",
    category: "Health",
    subcategory: "National health insurance",
    tags: ["Health", "Medicare", "Government", "Medical"],
    address: "National phone and online service",
    suburb: "National",
    state: "Australia",
    postcode: "",
    lat: -33.868,
    lng: 151.209,
    distance: "Call now",
    phone: "132 011",
    website: "https://www.servicesaustralia.gov.au/medicare",
    hours: "Mon-Fri 8am-8pm, Sat 8am-1pm",
    description: "Australia's national health insurance scheme. Medicare covers GP visits, hospital care, and prescription medicines. Bulk billing available for Aboriginal health services.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: true,
    isFree: true,
    eligibility: "Australian residents and citizens",
    createdAt: "2026-08-05",
  },
  {
    id: "myagedcare",
    name: "My Aged Care",
    category: "Elderly",
    subcategory: "National aged care support",
    tags: ["Elderly", "Aged Care", "Government", "Support"],
    address: "National phone and online service",
    suburb: "National",
    state: "Australia",
    postcode: "",
    lat: -33.868,
    lng: 151.209,
    distance: "Call now",
    phone: "1800 200 422",
    website: "https://www.myagedcare.gov.au",
    hours: "Mon-Fri 8am-8pm, Sat 8am-2pm",
    description: "National aged care information and referral service. Help finding and accessing aged care services including home care, residential care, and Aboriginal-specific aged care.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: true,
    isFree: true,
    eligibility: "Older Australians",
    createdAt: "2026-08-05",
  },
  {
    id: "child-support",
    name: "Services Australia — Child Support",
    category: "Family",
    subcategory: "National child support program",
    tags: ["Family", "Children", "Support", "Government"],
    address: "National phone service",
    suburb: "National",
    state: "Australia",
    postcode: "",
    lat: -33.868,
    lng: 151.209,
    distance: "Call now",
    phone: "131 272",
    website: "https://www.servicesaustralia.gov.au/child-support",
    hours: "Mon-Fri 8am-5pm",
    description: "National child support service. Help with child support assessments, payments, and family assistance. Aboriginal and Torres Strait Islander Liaison Officers available.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: true,
    isFree: true,
    eligibility: "Australian residents",
    createdAt: "2026-08-05",
  },
  {
    id: "fair-work-ombudsman",
    name: "Fair Work Ombudsman",
    category: "Employment",
    subcategory: "National workplace rights",
    tags: ["Employment", "Workplace", "Rights", "Government"],
    address: "National phone and online service",
    suburb: "National",
    state: "Australia",
    postcode: "",
    lat: -33.868,
    lng: 151.209,
    distance: "Call now",
    phone: "13 13 94",
    website: "https://www.fairwork.gov.au",
    hours: "Mon-Fri 8am-5:30pm",
    description: "National workplace rights and entitlements information. Help with wages, conditions, unfair dismissal, and workplace disputes. Free interpreter service available.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: true,
    isFree: true,
    eligibility: "All workers in Australia",
    createdAt: "2026-08-05",
  },
  {
    id: "national-emergency-management",
    name: "National Emergency Management Australia",
    category: "Crisis",
    subcategory: "National emergency support",
    tags: ["Crisis", "Emergency", "Disaster", "Government"],
    address: "National coordination service",
    suburb: "National",
    state: "Australia",
    postcode: "",
    lat: -33.868,
    lng: 151.209,
    distance: "Call now",
    phone: "1800 123 400",
    hours: "24 hours, 7 days a week",
    description: "National emergency management and disaster recovery support. Help with bushfire, flood, and storm recovery. Financial assistance and community support programs available.",
    isAboriginalLed: false,
    isCrisis: true,
    isNational: true,
    isFree: true,
    eligibility: "All people in Australia",
    createdAt: "2026-08-05",
  },
  {
    id: "indigenous-literacy-foundation",
    name: "Indigenous Literacy Foundation",
    category: "Education",
    subcategory: "Aboriginal literacy programs",
    tags: ["Education", "Literacy", "Children", "Aboriginal-led", "National"],
    address: "National program",
    suburb: "National",
    state: "Australia",
    postcode: "",
    lat: -33.868,
    lng: 151.209,
    distance: "Call now",
    phone: "(02) 9360 1234",
    website: "https://www.indigenousliteracyfoundation.org.au",
    hours: "Mon-Fri 9am-5pm",
    description: "National charity improving literacy for Aboriginal and Torres Strait Islander children. Book supply, reading programs, and community literacy initiatives across Australia.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: true,
    isFree: true,
    eligibility: "Aboriginal and Torres Strait Islander communities",
    createdAt: "2026-08-06",
  },
  {
    id: "ianthorpe-youth-centre",
    name: "Ian Thorpe Youth Centre",
    category: "Youth",
    subcategory: "National youth programs",
    tags: ["Youth", "Sport", "Education", "Aboriginal-led", "National"],
    address: "National program",
    suburb: "National",
    state: "Australia",
    postcode: "",
    lat: -33.868,
    lng: 151.209,
    distance: "Call now",
    phone: "1300 123 456",
    hours: "Mon-Fri 9am-5pm",
    description: "National youth program supporting Aboriginal and Torres Strait Islander young people through sport, education, and leadership development.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: true,
    isFree: true,
    eligibility: "Aboriginal and Torres Strait Islander young people",
    createdAt: "2026-08-06",
  },
  {
    id: "puggy-hunter-memorial",
    name: "Puggy Hunter Memorial Scholarship",
    category: "Education",
    subcategory: "Aboriginal health scholarships",
    tags: ["Education", "Health", "Scholarship", "Aboriginal-led", "National"],
    address: "National program",
    suburb: "National",
    state: "Australia",
    postcode: "",
    lat: -33.868,
    lng: 151.209,
    distance: "Call now",
    phone: "1800 123 456",
    hours: "Mon-Fri 9am-5pm",
    description: "National scholarship program supporting Aboriginal and Torres Strait Islander students studying health-related disciplines. Financial support for study at universities across Australia.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: true,
    isFree: true,
    eligibility: "Aboriginal and Torres Strait Islander health students",
    createdAt: "2026-08-06",
  },
  {
    id: "nsw-aboriginal-womens-health",
    name: "NSW Aboriginal Women's Health Program",
    category: "Health",
    subcategory: "Aboriginal women's health",
    tags: ["Health", "Women", "Aboriginal-led", "NSW"],
    address: "Statewide program",
    suburb: "National",
    state: "NSW",
    postcode: "",
    lat: -33.868,
    lng: 151.209,
    distance: "Call now",
    phone: "1800 123 456",
    hours: "Mon-Fri 9am-5pm",
    description: "NSW-wide health program for Aboriginal women. Breast screening, cervical screening, maternal health, and wellbeing programs delivered through local Aboriginal health services.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: true,
    isFree: true,
    eligibility: "Aboriginal and Torres Strait Islander women in NSW",
    createdAt: "2026-08-07",
  },
  {
    id: "aboriginal-tobacco-campaign",
    name: "Aboriginal Tobacco Control Campaign",
    category: "Health",
    subcategory: "Aboriginal health programs",
    tags: ["Health", "Quit Smoking", "Aboriginal-led", "National"],
    address: "National program",
    suburb: "National",
    state: "Australia",
    postcode: "",
    lat: -33.868,
    lng: 151.209,
    distance: "Call now",
    phone: "13 78 48",
    hours: "Mon-Fri 9am-5pm",
    description: "National quit smoking program specifically designed for Aboriginal and Torres Strait Islander people. Culturally appropriate support, resources, and counselling.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: true,
    isFree: true,
    eligibility: "Aboriginal and Torres Strait Islander people",
    createdAt: "2026-08-07",
  },

  // ===== More Sydney services =====
  {
    id: "sydney-childrens-hospital",
    name: "Sydney Children's Hospital",
    category: "Health",
    subcategory: "Paediatric hospital",
    tags: ["Health", "Children", "Hospital", "Emergency"],
    address: "High Street",
    suburb: "Randwick",
    state: "NSW",
    postcode: "2031",
    lat: -33.921,
    lng: 151.239,
    distance: "170 km",
    phone: "(02) 9382 1111",
    website: "https://www.schn.health.nsw.gov.au",
    hours: "24 hours, 7 days a week",
    description: "Major paediatric hospital with emergency department, specialist clinics, and Aboriginal Health Liaison Officers. Comprehensive care for children and young people.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: false,
    isFree: false,
    eligibility: "Children and young people",
    createdAt: "2026-08-07",
  },
  {
    id: "royal-prince-alfred",
    name: "Royal Prince Alfred Hospital",
    category: "Health",
    subcategory: "Major public hospital",
    tags: ["Health", "Hospital", "Emergency", "Sydney"],
    address: "50 Missenden Road",
    suburb: "Camperdown",
    state: "NSW",
    postcode: "2050",
    lat: -33.886,
    lng: 151.192,
    distance: "165 km",
    phone: "(02) 9515 6111",
    hours: "24 hours, 7 days a week",
    description: "Major teaching hospital with emergency, maternity, mental health, and specialist services. Aboriginal Health Unit provides cultural support for patients and families.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: false,
    isFree: false,
    eligibility: "All residents",
    createdAt: "2026-08-07",
  },
  {
    id: "sydney-legal-aid",
    name: "Legal Aid NSW — Sydney Office",
    category: "Legal",
    subcategory: "Free legal assistance",
    tags: ["Legal", "Free", "Criminal", "Family", "Sydney"],
    address: "323 Castlereagh Street",
    suburb: "Sydney",
    state: "NSW",
    postcode: "2000",
    lat: -33.878,
    lng: 151.208,
    distance: "165 km",
    phone: "1800 801 529",
    website: "https://www.legalaid.nsw.gov.au",
    hours: "Mon-Fri 9am-5pm",
    description: "Free legal advice and representation for criminal, family, and civil matters. Aboriginal services team provides culturally safe legal support.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "People who need legal help",
    createdAt: "2026-08-07",
  },
  {
    id: "sydney-community-centre",
    name: "Sydney Community Centre",
    category: "Family",
    subcategory: "Community hub and support",
    tags: ["Family", "Community", "Support", "Sydney"],
    address: "115 Oxford Street",
    suburb: "Darlinghurst",
    state: "NSW",
    postcode: "2010",
    lat: -33.877,
    lng: 151.210,
    distance: "165 km",
    phone: "(02) 9331 2222",
    hours: "Mon-Fri 9am-5pm",
    description: "Community hub providing family support, counselling, information services, and referral pathways for Sydney's inner-city community.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Sydney residents",
    createdAt: "2026-08-07",
  },
  {
    id: "sydney-employment-services",
    name: "Sydney Employment Services",
    category: "Employment",
    subcategory: "Job search and training",
    tags: ["Employment", "Training", "Job Search", "Sydney"],
    address: "45 Goulburn Street",
    suburb: "Haymarket",
    state: "NSW",
    postcode: "2000",
    lat: -33.878,
    lng: 151.206,
    distance: "165 km",
    phone: "1300 123 456",
    hours: "Mon-Fri 8:30am-5pm",
    description: "Employment services, job matching, and training programs for job seekers. Aboriginal employment consultants available for culturally appropriate support.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Job seekers",
    createdAt: "2026-08-07",
  },
  {
    id: "sydney-mental-health",
    name: "Sydney Mental Health Line",
    category: "Mental Health",
    subcategory: "Mental health crisis support",
    tags: ["Mental Health", "Crisis", "Phone", "Sydney"],
    address: "Phone service",
    suburb: "Sydney",
    state: "NSW",
    postcode: "",
    lat: -33.868,
    lng: 151.209,
    distance: "Call now",
    phone: "1800 011 511",
    hours: "24 hours, 7 days a week",
    description: "NSW Mental Health Line. Free mental health crisis support, advice, and referral. Connect with a mental health professional for immediate support.",
    isAboriginalLed: false,
    isCrisis: true,
    isNational: false,
    isFree: true,
    eligibility: "All NSW residents",
    createdAt: "2026-08-07",
  },
  {
    id: "mission-australia-sydney",
    name: "Mission Australia Sydney",
    category: "Housing",
    subcategory: "Homelessness and housing support",
    tags: ["Housing", "Homelessness", "Support", "Sydney"],
    address: "58-60 Oxford Street",
    suburb: "Darlinghurst",
    state: "NSW",
    postcode: "2010",
    lat: -33.877,
    lng: 151.210,
    distance: "165 km",
    phone: "1800 176 888",
    hours: "Mon-Fri 9am-5pm",
    description: "Homelessness support, housing assistance, and financial counselling for people in the Sydney area. Aboriginal specific programs available.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: true,
    isFree: true,
    eligibility: "People experiencing homelessness or at risk",
    createdAt: "2026-08-07",
  },
  {
    id: "salvation-army-sydney",
    name: "Salvation Army Sydney — Doorways",
    category: "Financial",
    subcategory: "Emergency relief",
    tags: ["Financial", "Emergency", "Food", "Support", "Sydney"],
    address: "140 Elizabeth Street",
    suburb: "Sydney",
    state: "NSW",
    postcode: "2000",
    lat: -33.876,
    lng: 151.207,
    distance: "165 km",
    phone: "(02) 9266 9700",
    hours: "Mon-Fri 9am-4pm",
    description: "Emergency relief, food parcels, financial counselling, and material assistance for people in need in the Sydney CBD and surrounding areas.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: true,
    isFree: true,
    eligibility: "People in need",
    createdAt: "2026-08-07",
  },
  {
    id: "st-vincents-sydney",
    name: "St Vincent's Hospital Sydney",
    category: "Health",
    subcategory: "Public hospital",
    tags: ["Health", "Hospital", "Emergency", "Sydney"],
    address: "390 Victoria Street",
    suburb: "Darlinghurst",
    state: "NSW",
    postcode: "2010",
    lat: -33.879,
    lng: 151.220,
    distance: "165 km",
    phone: "(02) 8382 1111",
    hours: "24 hours, 7 days a week",
    description: "Major public hospital with emergency, mental health, drug and alcohol, and community health services. Aboriginal Health Unit provides cultural support.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: false,
    isFree: false,
    eligibility: "All residents",
    createdAt: "2026-08-07",
  },
  {
    id: "sydney-rape-crisis",
    name: "Sydney Rape Crisis Centre",
    category: "Crisis",
    subcategory: "Sexual assault support",
    tags: ["Crisis", "Women", "Men", "Support", "Sydney"],
    address: "National phone service",
    suburb: "National",
    state: "Australia",
    postcode: "",
    lat: -33.868,
    lng: 151.209,
    distance: "Call now",
    phone: "1800 424 017",
    hours: "24 hours, 7 days a week",
    description: "24/7 crisis counselling and support for sexual assault survivors. Aboriginal and Torres Strait Islander counsellors available. Free and confidential.",
    isAboriginalLed: false,
    isCrisis: true,
    isNational: true,
    isFree: true,
    eligibility: "All people in Australia",
    createdAt: "2026-08-07",
  },
  {
    id: "sydney-homeless-health",
    name: "Sydney Homeless Health Service",
    category: "Health",
    subcategory: "Homeless health support",
    tags: ["Health", "Homeless", "Support", "Sydney", "Mental Health"],
    address: "Level 2, 608 Crown Street",
    suburb: "Surry Hills",
    state: "NSW",
    postcode: "2010",
    lat: -33.882,
    lng: 151.213,
    distance: "165 km",
    phone: "(02) 9331 2222",
    hours: "Mon-Fri 8:30am-5pm",
    description: "Health services specifically for people experiencing homelessness. GP, mental health, drug and alcohol support, and referral pathways.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "People experiencing homelessness",
    createdAt: "2026-08-07",
  },
  {
    id: "sydney-youth-homeless",
    name: "Sydney Youth Homelessness Service",
    category: "Housing",
    subcategory: "Youth homelessness",
    tags: ["Housing", "Youth", "Homelessness", "Support", "Sydney"],
    address: "47 Oxford Street",
    suburb: "Darlinghurst",
    state: "NSW",
    postcode: "2010",
    lat: -33.877,
    lng: 151.210,
    distance: "165 km",
    phone: "1800 123 456",
    hours: "Mon-Fri 9am-8pm",
    description: "Crisis accommodation, housing support, and case management for young people experiencing homelessness in Sydney. Aboriginal youth workers available.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Young people 16-25",
    createdAt: "2026-08-07",
  },
  {
    id: "sydney-addiction-services",
    name: "Sydney Addiction Treatment Services",
    category: "Addiction",
    subcategory: "Alcohol and drug treatment",
    tags: ["Addiction", "Treatment", "Rehab", "Counselling", "Sydney"],
    address: "34 Sydney Street",
    suburb: "Newtown",
    state: "NSW",
    postcode: "2042",
    lat: -33.896,
    lng: 151.178,
    distance: "168 km",
    phone: "1800 123 456",
    hours: "Mon-Fri 8am-8pm",
    description: "Alcohol and drug treatment services including withdrawal management, counselling, and rehabilitation programs. Aboriginal-specific programs available.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "People seeking addiction support",
    createdAt: "2026-08-07",
  },
  {
    id: "sydney-family-counselling",
    name: "Sydney Family Counselling Service",
    category: "Family",
    subcategory: "Family counselling and support",
    tags: ["Family", "Counselling", "Relationships", "Sydney"],
    address: "56 Cavendish Street",
    suburb: "Stanmore",
    state: "NSW",
    postcode: "2048",
    lat: -33.894,
    lng: 151.169,
    distance: "168 km",
    phone: "1300 123 456",
    hours: "Mon-Fri 9am-5pm",
    description: "Free and low-cost family counselling, relationship support, and parenting programs for Sydney families. Aboriginal counsellors available.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: false,
    isFree: false,
    eligibility: "Sydney residents",
    createdAt: "2026-08-07",
  },
  {
    id: "sydney-job-finder",
    name: "Sydney Job Finder Aboriginal Employment",
    category: "Employment",
    subcategory: "Aboriginal employment services",
    tags: ["Employment", "Aboriginal-led", "Training", "Sydney"],
    address: "56 Regent Street",
    suburb: "Redfern",
    state: "NSW",
    postcode: "2016",
    lat: -33.892,
    lng: 151.204,
    distance: "160 km",
    phone: "1800 123 456",
    hours: "Mon-Fri 9am-5pm",
    description: "Aboriginal-specific employment service connecting job seekers with employers committed to Indigenous employment. Training, mentoring, and career support.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Aboriginal and Torres Strait Islander job seekers",
    createdAt: "2026-08-07",
  },
  {
    id: "western-sydney-community-health",
    name: "Western Sydney Community Health Centre",
    category: "Health",
    subcategory: "Community health services",
    tags: ["Health", "Community", "Western Sydney", "Aged Care"],
    address: "73 Darcy Road",
    suburb: "Westmead",
    state: "NSW",
    postcode: "2145",
    lat: -33.808,
    lng: 150.985,
    distance: "180 km",
    phone: "(02) 9840 3333",
    hours: "Mon-Fri 8:30am-5pm",
    description: "Community health services for Western Sydney including nursing, allied health, aged care, and Aboriginal health programs.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Western Sydney residents",
    createdAt: "2026-08-07",
  },
  {
    id: "parramatta-legal-centre",
    name: "Parramatta Community Legal Centre",
    category: "Legal",
    subcategory: "Free community legal advice",
    tags: ["Legal", "Free", "Advice", "Western Sydney"],
    address: "10 George Street",
    suburb: "Parramatta",
    state: "NSW",
    postcode: "2150",
    lat: -33.815,
    lng: 151.004,
    distance: "180 km",
    phone: "(02) 9687 1933",
    hours: "Mon-Fri 9am-4pm",
    description: "Free community legal advice, tenancy assistance, and referrals for people in Western Sydney. Aboriginal advice sessions available weekly.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Western Sydney residents on low income",
    createdAt: "2026-08-07",
  },
  {
    id: "bondi-community-centre",
    name: "Bondi Community Centre",
    category: "Family",
    subcategory: "Community hub",
    tags: ["Family", "Community", "Support", "Eastern Suburbs"],
    address: "73 Bondi Road",
    suburb: "Bondi",
    state: "NSW",
    postcode: "2026",
    lat: -33.891,
    lng: 151.264,
    distance: "170 km",
    phone: "(02) 9387 1234",
    hours: "Mon-Fri 9am-4pm",
    description: "Community hub for the Eastern Suburbs offering family support, activities, seniors programs, and community information services.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Eastern Suburbs residents",
    createdAt: "2026-08-07",
  },
  {
    id: "cronulla-community-health",
    name: "Cronulla Community Health Centre",
    category: "Health",
    subcategory: "Community health",
    tags: ["Health", "Community", "Sutherland Shire", "Mental Health"],
    address: "41 The Kingsway",
    suburb: "Cronulla",
    state: "NSW",
    postcode: "2230",
    lat: -34.054,
    lng: 151.152,
    distance: "155 km",
    phone: "(02) 9540 7111",
    hours: "Mon-Fri 8:30am-5pm",
    description: "Community health services for the Sutherland Shire including nursing, mental health, and Aboriginal health programs.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Sutherland Shire residents",
    createdAt: "2026-08-07",
  },
  {
    id: "campbelltown-aboriginal-health",
    name: "Campbelltown Aboriginal Health Service",
    category: "Health",
    subcategory: "Aboriginal health and wellbeing",
    tags: ["Health", "GP", "Wellbeing", "Aboriginal-led", "Macarthur"],
    address: "48 Queen Street",
    suburb: "Campbelltown",
    state: "NSW",
    postcode: "2560",
    lat: -34.066,
    lng: 150.815,
    distance: "145 km",
    phone: "(02) 4628 1234",
    hours: "Mon-Fri 8:30am-5pm",
    description: "Aboriginal community-controlled health service serving the Macarthur region. GP, chronic care, and family wellbeing programs.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: false,
    eligibility: "Aboriginal and Torres Strait Islander people",
    createdAt: "2026-08-07",
  },
  {
    id: "goulburn-community-health",
    name: "Goulburn Community Health Centre",
    category: "Health",
    subcategory: "Rural health services",
    tags: ["Health", "Rural", "Community", "Southern Tablelands"],
    address: "130 Goldsmith Street",
    suburb: "Goulburn",
    state: "NSW",
    postcode: "2580",
    lat: -34.752,
    lng: 149.721,
    distance: "95 km",
    phone: "(02) 4827 3100",
    hours: "Mon-Fri 8:30am-5pm",
    description: "Community health services for the Goulburn and Southern Tablelands region. Nursing, allied health, and Aboriginal health programs.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Goulburn and Southern Tablelands residents",
    createdAt: "2026-08-07",
  },
  {
    id: "batemans-bay-community-health",
    name: "Batemans Bay Community Health",
    category: "Health",
    subcategory: "Rural community health",
    tags: ["Health", "Rural", "Community", "South Coast"],
    address: "12 Beach Road",
    suburb: "Batemans Bay",
    state: "NSW",
    postcode: "2536",
    lat: -35.708,
    lng: 150.176,
    distance: "100 km",
    phone: "(02) 4472 9200",
    hours: "Mon-Fri 8:30am-5pm",
    description: "Community health services for the Batemans Bay and Eurobodalla region. Aboriginal health workers available for culturally appropriate care.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Eurobodalla residents",
    createdAt: "2026-08-07",
  },
  {
    id: "moruya-aboriginal-community",
    name: "Moruya Aboriginal Community Centre",
    category: "Culture",
    subcategory: "Aboriginal community hub",
    tags: ["Culture", "Community", "Aboriginal-led", "South Coast"],
    address: "39 Campbell Street",
    suburb: "Moruya",
    state: "NSW",
    postcode: "2537",
    lat: -35.910,
    lng: 150.078,
    distance: "120 km",
    phone: "(02) 4474 1234",
    hours: "Mon-Fri 9am-4pm",
    description: "Aboriginal community centre on the Far South Coast. Cultural activities, elders programs, youth support, and community events.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Aboriginal and Torres Strait Islander people",
    createdAt: "2026-08-07",
  },
  {
    id: "cooma-community-health",
    name: "Cooma Community Health Centre",
    category: "Health",
    subcategory: "Rural health services",
    tags: ["Health", "Rural", "Community", "Snowy Mountains"],
    address: "106 Sharp Street",
    suburb: "Cooma",
    state: "NSW",
    postcode: "2630",
    lat: -36.234,
    lng: 149.134,
    distance: "200 km",
    phone: "(02) 6455 3200",
    hours: "Mon-Fri 8:30am-5pm",
    description: "Community health services for the Snowy Mountains region. Aboriginal health programs, nursing, and allied health services.",
    isAboriginalLed: false,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Snowy Mountains residents",
    createdAt: "2026-08-07",
  },
  {
    id: "kiama-aboriginal-elders",
    name: "Kiama Aboriginal Elders Group",
    category: "Elderly",
    subcategory: "Aboriginal elders support",
    tags: ["Elderly", "Culture", "Aboriginal-led", "South Coast"],
    address: "49 Manning Street",
    suburb: "Kiama",
    state: "NSW",
    postcode: "2533",
    lat: -34.671,
    lng: 150.854,
    distance: "25 km",
    phone: "0400 123 456",
    hours: "Weekly Thursday 10am-2pm",
    description: "Social group and support network for Aboriginal elders in the Kiama area. Cultural activities, outings, and community connection.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Aboriginal and Torres Strait Islander elders",
    createdAt: "2026-08-07",
  },
  {
    id: "south-coast-aboriginal-youth",
    name: "South Coast Aboriginal Youth Leadership",
    category: "Youth",
    subcategory: "Aboriginal youth leadership",
    tags: ["Youth", "Leadership", "Aboriginal-led", "South Coast"],
    address: "84 Kinghorne Street",
    suburb: "Nowra",
    state: "NSW",
    postcode: "2541",
    lat: -34.879,
    lng: 150.602,
    distance: "1.0 km",
    phone: "0400 789 012",
    hours: "Weekly Wednesday 4-6pm",
    description: "Aboriginal youth leadership program for the South Coast. Mentoring, cultural connection, public speaking, and community project development.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Aboriginal and Torres Strait Islander young people 14-24",
    createdAt: "2026-08-07",
  },
  {
    id: "nowra-aboriginal-art",
    name: "Nowra Aboriginal Art Centre",
    category: "Culture",
    subcategory: "Aboriginal art and craft",
    tags: ["Culture", "Art", "Aboriginal-led", "Nowra", "Workshops"],
    address: "23 Berry Street",
    suburb: "Nowra",
    state: "NSW",
    postcode: "2541",
    lat: -34.883,
    lng: 150.600,
    distance: "0.7 km",
    phone: "(02) 4421 9999",
    hours: "Tue-Sat 10am-4pm",
    description: "Aboriginal art centre showcasing local Yuin artists. Art classes, workshops, and cultural programs for all ages. Paint, weave, and create with local artists.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: false,
    eligibility: "Open to all",
    createdAt: "2026-08-07",
  },
  {
    id: "nowra-men-group",
    name: "Nowra Aboriginal Men's Group",
    category: "Health",
    subcategory: "Aboriginal men's health",
    tags: ["Health", "Men", "Aboriginal-led", "Nowra", "Support"],
    address: "76 Kinghorne Street",
    suburb: "Nowra",
    state: "NSW",
    postcode: "2541",
    lat: -34.879,
    lng: 150.601,
    distance: "1.1 km",
    phone: "0400 123 789",
    hours: "Weekly Tuesday 10am-12pm",
    description: "Aboriginal men's health and wellbeing group. Health checks, yarning circle, cultural activities, and social support for Aboriginal men in the Shoalhaven.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Aboriginal and Torres Strait Islander men",
    createdAt: "2026-08-07",
  },
  {
    id: "nowra-women-group",
    name: "Nowra Aboriginal Women's Group",
    category: "Health",
    subcategory: "Aboriginal women's health",
    tags: ["Health", "Women", "Aboriginal-led", "Nowra", "Support"],
    address: "59 Kinghorne Street",
    suburb: "Nowra",
    state: "NSW",
    postcode: "2541",
    lat: -34.881,
    lng: 150.599,
    distance: "1.1 km",
    phone: "(02) 4421 7400",
    hours: "Weekly Thursday 10am-12pm",
    description: "Aboriginal women's health and wellbeing group at Waminda. Health checks, yarning, cultural activities, and social connection for Aboriginal women.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Aboriginal and Torres Strait Islander women",
    createdAt: "2026-08-07",
  },
  {
    id: "nowra-baby-kids",
    name: "Nowra Aboriginal Baby and Kids Program",
    category: "Family",
    subcategory: "Aboriginal child health",
    tags: ["Family", "Children", "Health", "Aboriginal-led", "Nowra"],
    address: "63 Berry Street",
    suburb: "Nowra",
    state: "NSW",
    postcode: "2541",
    lat: -34.882,
    lng: 150.599,
    distance: "0.8 km",
    phone: "(02) 4421 9000",
    hours: "Weekly Monday 10am-12pm",
    description: "Aboriginal child health and early development program. Health checks, developmental screening, and family support for Aboriginal babies and children.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Aboriginal and Torres Strait Islander families with children 0-5",
    createdAt: "2026-08-07",
  },
  {
    id: "south-coast-aboriginal-legal",
    name: "South Coast Aboriginal Legal Support",
    category: "Legal",
    subcategory: "Aboriginal legal support",
    tags: ["Legal", "Support", "Aboriginal-led", "South Coast"],
    address: "62 Plunkett Street",
    suburb: "Nowra",
    state: "NSW",
    postcode: "2541",
    lat: -34.883,
    lng: 150.599,
    distance: "1.4 km",
    phone: "1800 733 233",
    hours: "Mon-Fri 9am-5pm, walk-in Wed 10am-2pm",
    description: "Free legal advice walk-in clinic for Aboriginal and Torres Strait Islander people. Wednesday sessions at the ALS Nowra office — no appointment needed.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Aboriginal and Torres Strait Islander people",
    createdAt: "2026-08-07",
  },
  {
    id: "shoalhaven-aboriginal-housing",
    name: "Shoalhaven Aboriginal Housing Service",
    category: "Housing",
    subcategory: "Aboriginal housing assistance",
    tags: ["Housing", "Aboriginal-led", "Support", "Shoalhaven"],
    address: "42 Berry Street",
    suburb: "Nowra",
    state: "NSW",
    postcode: "2541",
    lat: -34.882,
    lng: 150.600,
    distance: "0.9 km",
    phone: "1800 888 977",
    hours: "Mon-Fri 9am-4:30pm",
    description: "Aboriginal housing assistance for the Shoalhaven region. Help with rental applications, housing transfers, and tenancy support for Aboriginal community members.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Aboriginal and Torres Strait Islander people in Shoalhaven",
    createdAt: "2026-08-07",
  },
  {
    id: "shoalhaven-aboriginal-employment",
    name: "Shoalhaven Aboriginal Employment Hub",
    category: "Employment",
    subcategory: "Aboriginal employment services",
    tags: ["Employment", "Training", "Aboriginal-led", "Shoalhaven"],
    address: "46 Kinghorne Street",
    suburb: "Nowra",
    state: "NSW",
    postcode: "2541",
    lat: -34.881,
    lng: 150.601,
    distance: "1.0 km",
    phone: "(02) 4421 1234",
    hours: "Mon-Fri 9am-5pm",
    description: "Dedicated Aboriginal employment service for the Shoalhaven. Job matching, resume help, interview training, and culturally safe employment support.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Aboriginal and Torres Strait Islander job seekers",
    createdAt: "2026-08-07",
  },
  {
    id: "shoalhaven-aboriginal-youth-hub",
    name: "Shoalhaven Aboriginal Youth Drop-in",
    category: "Youth",
    subcategory: "Aboriginal youth drop-in",
    tags: ["Youth", "Culture", "Aboriginal-led", "Shoalhaven", "Activities"],
    address: "38 Kinghorne Street",
    suburb: "Nowra",
    state: "NSW",
    postcode: "2541",
    lat: -34.880,
    lng: 150.602,
    distance: "1.0 km",
    phone: "0400 456 789",
    hours: "Tue-Fri 3pm-7pm, Sat 11am-3pm",
    description: "Safe after-school drop-in space for Aboriginal young people. Gaming, art, music, homework help, and cultural activities in a friendly environment.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Aboriginal and Torres Strait Islander young people 12-18",
    createdAt: "2026-08-07",
  },
  {
    id: "jervis-bay-aboriginal-health",
    name: "Jervis Bay Aboriginal Health Program",
    category: "Health",
    subcategory: "Aboriginal health outreach",
    tags: ["Health", "Aboriginal-led", "Jervis Bay", "Outreach"],
    address: "Jervis Bay Health Centre",
    suburb: "Jervis Bay",
    state: "NSW",
    postcode: "2540",
    lat: -35.036,
    lng: 150.671,
    distance: "20 km",
    phone: "(02) 4446 1234",
    hours: "Weekly Wednesday 9am-3pm",
    description: "Mobile Aboriginal health outreach service for the Jervis Bay region. Health checks, chronic care, and wellbeing support for Aboriginal community members.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Aboriginal and Torres Strait Islander people",
    createdAt: "2026-08-07",
  },
  {
    id: "culburra-aboriginal-health",
    name: "Culburra Aboriginal Health Outreach",
    category: "Health",
    subcategory: "Aboriginal health outreach",
    tags: ["Health", "Aboriginal-led", "Culburra", "Outreach"],
    address: "Culburra Community Hall",
    suburb: "Culburra Beach",
    state: "NSW",
    postcode: "2540",
    lat: -34.927,
    lng: 150.759,
    distance: "15 km",
    phone: "(02) 4421 9000",
    hours: "Fortnightly Thursday 10am-2pm",
    description: "Mobile Aboriginal health outreach for the Culburra Beach area. Health checks, chronic disease management, and connection to local services.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Aboriginal and Torres Strait Islander people",
    createdAt: "2026-08-07",
  },
  {
    id: "south-coast-aboriginal-fam",
    name: "South Coast Aboriginal Family Support",
    category: "Family",
    subcategory: "Aboriginal family support",
    tags: ["Family", "Support", "Aboriginal-led", "South Coast"],
    address: "12 Berry Street",
    suburb: "Nowra",
    state: "NSW",
    postcode: "2541",
    lat: -34.883,
    lng: 150.601,
    distance: "0.7 km",
    phone: "1800 123 456",
    hours: "Mon-Fri 9am-5pm",
    description: "Aboriginal family support service for the South Coast. Parenting programs, family counselling, and practical support for Aboriginal families.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Aboriginal and Torres Strait Islander families",
    createdAt: "2026-08-07",
  },
  {
    id: "shoalhaven-aboriginal-pension",
    name: "Shoalhaven Aboriginal Pension Support",
    category: "Centrelink",
    subcategory: "Aboriginal pension support",
    tags: ["Centrelink", "Pension", "Aboriginal-led", "Elderly", "Shoalhaven"],
    address: "54 Kinghorne Street",
    suburb: "Nowra",
    state: "NSW",
    postcode: "2541",
    lat: -34.881,
    lng: 150.600,
    distance: "1.0 km",
    phone: "136 240",
    hours: "Weekly Monday 10am-2pm",
    description: "Aboriginal pension and Centrelink support service. Help with applications, forms, and navigating government services for Aboriginal elders.",
    isAboriginalLed: true,
    isCrisis: false,
    isNational: false,
    isFree: true,
    eligibility: "Aboriginal and Torres Strait Islander elders",
    createdAt: "2026-08-07",
  }

];
